sudo: required

services:
  - docker

before_install:
  - docker build  -t eviatenne/docker-react -f Dockerfile.dev .

script:
  - docker run eviatenne/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-244308422964"
  bucket_path: "docker"
  on:
    branch: master